src/main/resources/jseont_sitemap/xml/sitemap.index.jsp
https://jira.jahia.org/browse/BACKLOG-15618
Generate sitemap.index in default language only, fix paths when with context
=> Backlog 15618 Generate index in default language only

src/main/java/org/jahia/modules/sitemap/utils/QueryHelper.java, src/main/java/org/jahia/modules/sitemap/utils/VanityUrls.java, src/main/resources/META-INF/sitemap.tld, src/main/resources/common/sitemap-entry.jsp, src/main/resources/jseont_sitemap/xml/sitemap.jsp, src/main/resources/jseont_sitemapResource/xml/sitemapResource.jsp
https://jira.jahia.org/browse/BACKLOG-15619
* Add sitemap.xml for site
* Add check for nodes that have separate sitemaps and exclude it and descendants from the sitemap entries
=> BACKLOG-15619: Add sitemap.xml for site and filter nodes with separate sitemap

README.md, pom.xml, src/main/java/org/jahia/modules/sitemap/config/ConfigService.java, src/main/java/org/jahia/modules/sitemap/config/impl/ConfigServiceImpl.java, src/main/java/org/jahia/modules/sitemap/constant/SitemapConstant.java, src/main/java/org/jahia/modules/sitemap/job/SitemapBackgroundJob.java, src/main/java/org/jahia/modules/sitemap/utils/ConfigServiceUtils.java, src/main/java/org/jahia/modules/sitemap/utils/VanityUrls.java, src/main/resources/META-INF/configuration/org.jahia.modules.sitemap.config.impl.ConfigServiceImpl.cfg, src/main/resources/META-INF/sitemap.tld, src/test/java/org/jahia/modules/sitemap/config/ConfigServiceTest.java
https://jira.jahia.org/browse/BACKLOG-15616
* Added Included Content Type to the configuration file
* Updated Readme file with deployment instructions
* Able to read config properties from the JSP
* Refactor code to handle empty values since this is exposed to user input
* Updated pom to copy the cfg
=> Backlog-15616: Sitemap configuration

src/main/java/org/jahia/modules/sitemap/utils/QueryHelper.java, src/main/resources/META-INF/sitemap.tld, src/main/resources/jseont_sitemap/xml/sitemap.jsp, src/main/resources/jseont_sitemapResource/xml/sitemapResource.jsp, src/main/resources/resources/JahiaSitemap.properties, src/main/resources/resources/JahiaSitemap_de.properties, src/main/resources/resources/JahiaSitemap_en.properties, src/main/resources/resources/JahiaSitemap_fr.properties
https://jira.jahia.org/browse/BACKLOG-15619
* Fix visibility of resources with no live guest permission
* Fix/add translation for german, french; Modified mixin labels
I have considered the following implications of my change:
=> Backlog 15619 fix live users

pom.xml
https://jira.jahia.org/browse/BACKLOG-15616
* Fix typo in the pom
=> BACKLOG-15616: Fix typo in pom

tests/cypress/page-object/edit.page.ts, tests/warmup-manifest-snapshot.yml, tests/yarn.lock
https://jira.jahia.org/browse/BACKLOG-15584
Fix-up the nightly build to use the SNAPSHOT version as we had a successful build the artifact is pushed.
=> BACKLOG-15584: Fixing up the nightly build and slight update the slider portion.

src/main/java/org/jahia/modules/sitemap/filter/RobotsFilter.java, src/main/resources/META-INF/definitions.cnd, src/main/resources/resources/JahiaSitemap_de.properties, src/main/resources/resources/JahiaSitemap_en.properties, src/main/resources/resources/JahiaSitemap_fr.properties
https://jira.jahia.org/browse/BACKLOG-15108
Add filter to create met tag for robots
=> Backlog 15108 robots filter

README.md
https://jira.jahia.org/browse/BACKLOG-15619
Update sitemap README.md
=> BACKLOG-15619: Update README.md

pom.xml, tests/cypress/fixtures/C3218086/sitemap.index.urlpath.json, tests/cypress/fixtures/C3218088/sitemap.index.urlpath.json, tests/cypress/fixtures/C3218089/sitemap.index.urlpath.json, tests/cypress/integration/digitall.home.spec.ts, tests/cypress/integration/mysite.home.spec.ts, tests/cypress/page-object/edit.page.ts, tests/cypress/page-object/site.home.page.ts, tests/cypress/support/commands.ts, tests/cypress/support/utilites.ts
https://jira.jahia.org/browse/BACKLOG-15637
A bit of re-factor plus add in the test cases for C3128086 per the test rail
Updated per the latest PR to add C3218088 and C3218089 as well in this PR
Simplified the scenarios for both so don't leverage the "digitall" project at all.
=> BACKLOG-15637 add-in the C3218086 C3218088 C3218089 test-case with additional functionalities

README.md, src/main/resources/META-INF/configuration/org.jahia.modules.sitemap.config.impl.ConfigServiceImpl.cfg
https://jira.jahia.org/browse/BACKLOG-15826
Fix typos on mixin types
=> BACKLOG-15826: Fix typo on mixin types

src/main/resources/resources/JahiaSitemap_fr.properties
https://jira.jahia.org/browse/BACKLOG-15732
Fix french translation
=> BACKLOG-15732: French translation fix

tests/package.json, tests/yarn.lock
https://jira.jahia.org/browse/PROJECT-XXX
Ssri security issue need to upgrade the webpack version.
=> Simple fix on security for ssri 

pom.xml
https://jira.jahia.org/browse/BACKLOG-15102
Update the parent pom to 8.0.3
=> BACKLOG-15102: Update parent pom to 8.0.3.0-SNAPSHOT

.circleci/config.yml
https://jira.jahia.org/browse/BACKLOG-15915
Per discussion in meeintg
Changing the circle-ci AUDITCI_LEVEL to high
=> BACKLOG-15915: Updating config.yml to only block PR on high vul.

src/main/resources/common/sitemap-entry.jsp
https://jira.jahia.org/browse/BACKLOG-15911
Update the hreflang to use dash formatted locale.
=> BACKLOG-15911: Update the underscore to dash for hreflang.

README.md
https://jira.jahia.org/browse/BACKLOG-15915
Trivial readme changes.
=> BACKLOG-15915: Updating the readme based on the new business decision on file names

src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-15890
Added missing French and German translations for description (helper text).
=> BACKLOG-15890 : added French and German translations for description

.circleci/config.yml, tests/provisioning-manifest-build.yml, tests/provisioning-manifest-snapshot.yml
https://jira.jahia.org/browse/BACKLOG-16041
Provision nightly with correct snapshot
=> BACKLOG-16041 Import and deploy sitemap snapshot

src/main/resources/javascript/locales/en.json
Update RB for sitemap to display search engines instead of google
https://jira.jahia.org/browse/BACKLOG-15872
=> BACKLOG-15872 - Update labels for sitemap

src/main/resources/META-INF/patches/groovy/4.0.0-migrateSitemap.started.groovy
https://jira.jahia.org/browse/QA-14209
=> QA-14209 : execute migration script only on the processing server

.github/workflows/on-merge.yml
=> Fixed incorrect branch for publish

src/javascript/components/SitemapPanel.scss, src/javascript/components/SitemapPanelApp.jsx, src/javascript/components/SitemapPanelHeader/SitemapPanelHeader.jsx, src/javascript/components/gqlMutations.js, src/javascript/components/gqlQueries.js, src/javascript/components/panelSections/SitemapIndexLink/SitemapIndexLink.jsx, src/javascript/hooks/graphql/useGetSitemapUrl.js, src/main/java/org/jahia/modules/sitemap/filter/SitemapWebFilter.java, src/main/java/org/jahia/modules/sitemap/graphql/api/GqlSitemapQueries.java, src/main/java/org/jahia/modules/sitemap/utils/Utils.java, src/main/resources/META-INF/definitions.cnd, src/main/resources/META-INF/urlrewrite-sitemap.xml, src/main/resources/common/sitemap-xml.jsp, src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json, src/main/resources/jseomix_sitemap/xml/sitemap.sitemap.jsp
- fix settings panel to generate valid url.
- Simplify url rewrite rule
- Use stored hostname from settings as url prefix in sitemap.
=> BACKLOG-16952 

.github/workflows/on-code-change.yml, src/main/resources/common/sitemap-xml.jsp, tests/cypress/integration/publishUnpublish.spec.ts, tests/cypress/utils/waitUntilRefresh.ts
This restores changes done in: https://github.com/Jahia/sitemap/pull/97
=> BACKLOG-16963: Fixed incorrect namespace for xmlns

src/javascript/components/SitemapPanelHeader/SitemapPanelHeader.jsx, src/main/java/org/jahia/modules/sitemap/utils/Utils.java, src/main/resources/META-INF/sitemap.tld, src/main/resources/jseomix_sitemap/xml/sitemap.sitemap.jsp, tests/cypress/integration/activeLanguage.spec.ts
https://jira.jahia.org/browse/BACKLOG-16961
=> BACKLOG-16961 : Improve the way the sitemap.xml file is generated

src/main/resources/jseomix_sitemap/xml/sitemap.sitemap.jsp
remove double // in sitemap.xml urls
=> BACKLOG-16952 : remove double // in sitemap url

src/javascript/components/SitemapPanelApp.jsx
Add small check to validate url format
=> BACKLOG-16952 : add check on url validity

.github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, pom.xml, src/main/java/org/jahia/modules/sitemap/config/ConfigService.java, src/main/java/org/jahia/modules/sitemap/config/impl/ConfigServiceImpl.java, src/main/java/org/jahia/modules/sitemap/constant/SitemapConstant.java, src/main/resources/META-INF/configurations/org.jahia.modules.sitemap.config.impl.ConfigServiceImpl.cfg, tests/cypress/fixtures/graphql/jcrPublishNode.graphql, tests/cypress/integration/activeLanguage.spec.ts, tests/cypress/integration/publishUnpublish.spec.ts, tests/cypress/integration/xml/sitemap.lang.spec.ts, tests/provisioning-manifest-build.yml, tests/provisioning-manifest-snapshot.yml
- Updated the CI config to be compatible with this branch
- Removed an unused setting from the configuration file
=> BACKLOG-16975: Removed unnecessary configuration from sitemap

src/main/java/org/jahia/modules/sitemap/config/ConfigService.java, src/main/java/org/jahia/modules/sitemap/config/impl/ConfigServiceImpl.java, src/main/java/org/jahia/modules/sitemap/constant/SitemapConstant.java, src/main/resources/META-INF/configurations/org.jahia.modules.sitemap.config.impl.ConfigServiceImpl.cfg
https://jira.jahia.org/browse/BACKLOG-16975
=> BACKLOG-16975: Removed unused configuration properties

.github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml
The objective is to match the name of the environment variable that is made available as an organization secret
=> Fixed incorrect environment variable name

.github/workflows/manual-run.yml, .github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml
=> Migration to the GitHub Action v2

pom.xml
https://jira.jahia.org/browse/QA-14435
Export the package of the sitemap tags util class, so that the tags can be used in another module
I have considered the following implications of my change:
=> QA-14435: export packages to use sitemap tags in custom modules

pom.xml
This is a follow-up to #145 
https://jira.jahia.org/browse/QA-14435
=> QA-14435: export packages to use sitemap tags in custom modules (#145)

src/main/java/org/jahia/modules/sitemap/utils/Utils.java
https://jira.jahia.org/browse/QA-14644
Wrong encoding used for locales with region
I have considered the following implications of my change:
=> QA-14644 Dadicated sitemap is not displayed for locales with region

src/main/resources/common/sitemap-xml.jsp
https://jira.jahia.org/browse/QA-14642
=> QA-14642: Fix hreflang use hyphens instead of underscores.

pom.xml
https://jira.jahia.org/browse/TECH-1092
=> TECH-1092: Adding graphql-dxm-provider dependency

tests/cypress/integration/xml/sitemap.encoding.ts
https://jira.jahia.org/browse/BACKLOG-20838
=> BACKLOG-20838: Fix nightly tests.

src/main/java/org/jahia/modules/sitemap/utils/Utils.java
https://jira.jahia.org/browse/QA-14864
=> QA-14864 : use scroll query to get all pages for the sitemap

src/main/java/org/jahia/modules/sitemap/config/SitemapConfigService.java, src/main/java/org/jahia/modules/sitemap/config/impl/ConfigServiceImpl.java, src/main/java/org/jahia/modules/sitemap/constant/SitemapConstant.java, src/main/java/org/jahia/modules/sitemap/services/impl/SitemapServiceImpl.java, src/main/java/org/jahia/modules/sitemap/utils/Utils.java, src/main/resources/META-INF/configurations/org.jahia.modules.sitemap.config.impl.ConfigServiceImpl.cfg, src/main/resources/META-INF/sitemap.tld, src/main/resources/common/sitemap-xml.jsp
https://jira.jahia.org/browse/QA-14869
=> QA-14869 : restore sitemap.included-content-types config support

src/main/java/org/jahia/modules/sitemap/config/impl/ConfigServiceImpl.java
https://jira.jahia.org/browse/QA-14869
=> QA-14869 : set default values for included content types

.github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, package.json, pom.xml, webpack.config.js, yarn.lock
https://jira.jahia.org/browse/TECH-1275
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release
I have considered the following implications of my change:
=> TECH-1275: Add SBOM creation

tests/provisioning-manifest-build.yml, tests/provisioning-manifest-snapshot.yml
https://jira.jahia.org/browse/BACKLOG-21396
=> BACKLOG-21396: Remove temporary fix should be work now with jContent 3x.

pom.xml
https://jira.jahia.org/browse/TECH-1243
=> TECH-1243: fix expression

.github/workflows/nightly-cluster.yml, .github/workflows/nightly-standalone-release.yml, .github/workflows/nightly-standalone-snapshot.yml
=> Split pagerduty reporting

package.json, src/javascript/components/SitemapPanelHeader/SitemapPanelHeader.jsx, yarn.lock
https://jira.jahia.org/browse/QA-15023
=> QA-15023: Change icon for "generate sitemap" button

tests/cypress/integration/xml/sitemap.encoding.ts
https://jira.jahia.org/browse/BACKLOG-22137
- Skip check encoding test until the issue is fixed
=> BACKLOG-22137: Skip check encoding test

pom.xml
https://jira.jahia.org/browse/BACKLOG-22343
Add missing package dependencies version range
=> BACKLOG-22343: Fix graphql dependency

src/javascript/components/SitemapPanelApp.jsx, src/javascript/components/gqlMutations.js, src/main/java/org/jahia/modules/sitemap/job/SitemapCreationJob.java, src/main/java/org/jahia/modules/sitemap/utils/Utils.java, src/main/resources/META-INF/definitions.cnd, src/main/resources/META-INF/sitemap.tld, src/main/resources/jseomix_sitemap/xml/sitemap.sitemap.jsp, tests/cypress/integration/activeLanguage.spec.ts, tests/cypress/integration/config/configureSitemapViaApi.spec.ts, tests/cypress/integration/lifecycleChecks.spec.ts, tests/cypress/integration/publishUnpublish.spec.ts, tests/cypress/integration/xml/sitemap.encoding.ts, tests/cypress/integration/xml/sitemap.lang.spec.ts, tests/cypress/integration/xml/sitemap.root.urlRewrite.spec.ts, tests/cypress/integration/xml/sitemap.spec.ts, tests/cypress/utils/configureSitemap.ts
https://jira.jahia.org/browse/QA-15082
Deprecate the property sitemapHostname in the definition.cnd
Do not use the property anymore in the code
Improve the logs to have better information when something is wrong with the properties used for sitemap
=> QA-15082: remove sitemapHostname property uses and improve logs

src/main/resources/META-INF/definitions.cnd
https://jira.jahia.org/browse/QA-15082
=> QA-15082: remove autocreated on sitemapHostname

src/main/java/org/jahia/modules/sitemap/job/SitemapCreationJob.java
https://jira.jahia.org/browse/QA-15098
Update URI scheme to https so that the sitemap is displayed with XML structure in the browser.
=> QA-15098: Update URI scheme to https

src/main/java/org/jahia/modules/sitemap/services/impl/SitemapServiceImpl.java
https://jira.jahia.org/browse/BACKLOG-22669
=> BACKLOG-22669 : prevent error at when jahia is stopped

package.json, pom.xml
https://jira.jahia.org/browse/BACKLOG-22688
=> BACKLOG-22688: Set version of the module to 5.3.1

src/main/java/org/jahia/modules/sitemap/listeners/SitemapSiteListener.java
The previous message made it very hard to understand what was happening.
=> TECH-1830: better handle logs when importing site

.github/workflows/manual-run.yml, .github/workflows/nightly-cluster.yml, .github/workflows/nightly-standalone-release.yml, .github/workflows/nightly-standalone-snapshot.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml, .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
Upgrade actions
=> TECH-1639 Upgrade actions
